apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-dind-var-lib
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeMode: Filesystem
