# https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
---
alertmanager:
  ingress:
    enabled: true
    # annotations:
    #   kubernetes.io/ingress.class: nginx-01
    pathType: Prefix
grafana:
  ingress:
    enabled: true
    # annotations:
    #   kubernetes.io/ingress.class: nginx-01
  plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
prometheus:
  ingress:
    enabled: true
    # annotations:
    #   kubernetes.io/ingress.class: nginx-01
    pathType: Prefix